### ISSUE TITLE
Connecting to invalid output 1 of source node loss/conv2d_50_loss/StatefulPartitionedCall which has 1 outputs.

### ISSUE THREAD

**Issue by JHyellow** [strvcom/strv-ml-mask2face#7]
Traceback (most recent call last):
  File "H:/no_mask/strv-ml-mask2face-master/test.py", line 85, in <module>
    model.train(epochs=training_epochs, batch_size=batch_size, loss_function='ssim_l1_loss', learning_rate=0.1)
  File "H:\no_mask\strv-ml-mask2face-master\utils\model.py", line 133, in train
    history = self.model.fit(train_dataset, validation_data=valid_dataset, epochs=epochs, callbacks=callbacks)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training_v1.py", line 785, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 666, in fit
    steps_name='steps_per_epoch')
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 205, in model_iteration
    steps_name='validation_steps')
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training_utils.py", line 1795, in infer_steps_for_dataset
    size = K.get_value(cardinality.cardinality(dataset))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\backend.py", line 3310, in get_value
    return x.eval(session=get_session((x,)))
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\backend.py", line 527, in get_session
    _initialize_variables(session)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\backend.py", line 939, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'training/Adam/gradients/gradients/loss/conv2d_50_loss/StatefulPartitionedCall_grad/PartitionedCall': Connecting to invalid output 1 of source node loss/conv2d_50_loss/StatefulPartitionedCall which has 1 outputs.

I have met this problem and I can't solve it, can someone help me?Thanks.

**Comment by AshishVishnu2747** [comment]
Facing same issue.
